### ISSUE TITLE
Seems to choke on Java UUIDs

### ISSUE THREAD

**Issue by joshuafcole** [mortalapeman/birch-lt#1]
Awesome plugin. Couldn't wait to use it for visualizing (and perhaps in the future editing) my little component entity system based project. Unfortunately, it seems to crash when I try to examine an object containing a UUID.

```
Error: Unreadable form
    at Error (<anonymous>)
    at a (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:21986:11)
    at b (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:21990:14)
    at eval (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22201:37)
    at cljs.reader.read_dispatch (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22127:14)
    at cljs.reader.read_delimited_list (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22117:33)
    at cljs.reader.read_map (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22143:43)
    at cljs.reader.read_delimited_list (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22117:33)
    at cljs.reader.read_map (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22143:43)
    at cljs.reader.read (file:///home/josh/bin/Programs/LightTable/core/node_modules/lighttable/bootstrap.js:22300:39)
```

**Comment by joshuafcole** [comment]
Example result:

```
{:id #uuid "3d71ce2f-b6bf-41a0-bb73-98b8d61bc5a6", :systems {:player-control {:on-key-down #<player_control$player_control$fn__13965 tetsujin.systems.player_control$player_control$fn__13965@5a16f520>}, :render {:state {:engine #<Atom@7ef3586b: {:shape #<ShapeRenderer com.badlogic.gdx.graphics.glutils.ShapeRenderer@7cdaeba1>}>}, :init #<render$render$fn__14012 tetsujin.systems.render$render$fn__14012@442aec4a>, :tick #<render$render$fn__14014 tetsujin.systems.render$render$fn__14014@bd2a4f9>}}, :entities {#uuid "5a5b2cd3-d526-40b5-b6c8-ea8f46dbe26e" #<Atom@57fe31aa: {:id #uuid "5a5b2cd3-d526-40b5-b6c8-ea8f46dbe26e", :components {:position {:y 0, :x 64}, :render {:renderer #<block$render tetsujin.renderers.block$render@4c22f3b3>}}, :tags []}>, #uuid "3c62c31b-cc2d-45fc-b32c-8db70fb7fbf1" #<Atom@5290538d: {:id #uuid "3c62c31b-cc2d-45fc-b32c-8db70fb7fbf1", :components {:position {:x 128, :y 30}, :player-controlled {:speed 2}, :render {:renderer #<pacman$render tetsujin.renderers.pacman$render@4c44fa7>}}, :tags []}>, #uuid "c8a1f14b-9ecb-47c4-bee0-af612db445d7" #<Atom@6fa2ff02: {:id #uuid "c8a1f14b-9ecb-47c4-bee0-af612db445d7", :components {:position {:x 32, :y 30}, :player-controlled {:speed 2}, :render {:renderer #<pacman$render tetsujin.renderers.pacman$render@4c44fa7>}}, :tags []}>}, :last-ticked 1410240508444, :started? true}
```

**Comment by mortalapeman** [comment]
I suppose a quick fix for this would be to find all instances of #uuid and either remove that string or quote it plus it's value. I'll have to think about this one.
